

# CHOOSE 'CECHA CIĄGŁA, CECHA NASTĘPNA, PUNKTOWA

# IF PUNKTOWA - INPUT X NUM

#IF CIĄGŁA, NASTĘPNA - INPUT (X - Y), (X - Y)

# INPUT NUM OF - Ni, CZYLI ILOŚĆ

# COUNT - ŚREDNIA ARYTMETYCZNA
# 
# COUNT - ŚRODEK PRZEDZIAŁÓW - ŚREDNIA ARYTMETYCZNA
# 
# COUNT -  (ŚRODEK PRZEDZIAŁÓW - ŚREDNIA ARYTMETYCZNA)^2 * Ni



# IF CIĄGŁA, NASTĘPNA - COUNT 'ŚRODEK PRZEDZIAŁÓW'
